from TreeVisitor import TreeVisitor
from TreeParser import TreeParser


class UnknownIdentifier(Exception):
    pass


class MyTreeVisitor(TreeVisitor):
    """Visitor that evaluates an expression. Derives and overrides methods
    from TreeVisitor (generated by ANTLR4)."""
    def __init__(self):
        pass

    def visitNode(self, ctx):
        if len(ctx.expr) == 2:
            return self.visit(ctx.expr(0)) and self.visit(ctx.expr(1))
        else:
            return False

    def visitTopper(self, ctx):
        return self.visit(ctx.expr())

    
    def visitLeaf(self, ctx):
        return True
